name: Node.js Verify

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: NPM test
        status: queued
        output: |
          {"summary": "Preparing the test" }
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: NPM test
        status: in_progress
        output: |
          {"summary": "Running the test" }
    - run: npm run build --if-present
    - id: test
      run: npm test
      env:
        CI: true
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: NPM test
        conclusion: ${{ job.status }}
        output: |
          {"summary": "${{ steps.test.outputs.summary }}" }
